# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10

# Mod Properties
mod_version=0.0.20
maven_group=org.codeberg.zenxarch.zombies
archives_base_name=zombies_zenxarch

# Dependencies
fabric_version=0.115.1+1.21.1
sbl_version=1.16.7