# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=25w37a
yarn_mappings=25w37a+build.2
loader_version=0.17.2

# Mod Properties
mod_version=0.0.31
maven_group=org.codeberg.zenxarch.zombies
archives_base_name=zombies_zenxarch

# Dependencies
fabric_version=0.133.5+1.21.9
sbl_mc_version=1.21.7
sbl_version=1.16.10