# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=0.0.35
maven_group=org.codeberg.zenxarch.zombies
archives_base_name=zombies_zenxarch

# Dependencies
fabric_version=0.133.14+1.21.9
sbl_mc_version=1.21.9
sbl_version=1.16.11
