pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

include('zombie_brain', 'mob_variants_api', 'common', 'default_zombies')

rootProject.name = 'zombies'
