use-grammars = { only = [ "json","gradle","java","toml" ] }

[[language]]
name = "java"
# formatter = {command = "clang-format",args = ["--assume-filename=.java"]}
# language-servers = { {name = "jdtls",command = "jdtls"} }
# auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true
